// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wia
int wia(const int i);
RcppExport SEXP sparsetsmat_wia(SEXP iSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const int >::type i(iSEXP );
        int __result = wia(i);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stsm_xt_sqi_ij
Rcpp::IntegerVector stsm_xt_sqi_ij(const Rcpp::IntegerVector x_date, const Rcpp::IntegerVector i_idx, const Rcpp::IntegerVector j_idx, const Rcpp::IntegerVector id_idx, const Rcpp::IntegerVector id_noc, const int backfill);
RcppExport SEXP sparsetsmat_stsm_xt_sqi_ij(SEXP x_dateSEXP, SEXP i_idxSEXP, SEXP j_idxSEXP, SEXP id_idxSEXP, SEXP id_nocSEXP, SEXP backfillSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type x_date(x_dateSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type i_idx(i_idxSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type j_idx(j_idxSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type id_idx(id_idxSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type id_noc(id_nocSEXP );
        Rcpp::traits::input_parameter< const int >::type backfill(backfillSEXP );
        Rcpp::IntegerVector __result = stsm_xt_sqi_ij(x_date, i_idx, j_idx, id_idx, id_noc, backfill);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stsm_xt_sqd_ij
Rcpp::IntegerVector stsm_xt_sqd_ij(const Rcpp::DoubleVector x_date, const Rcpp::DoubleVector i_idx, const Rcpp::IntegerVector j_idx, const Rcpp::IntegerVector id_idx, const Rcpp::IntegerVector id_noc, const int backfill);
RcppExport SEXP sparsetsmat_stsm_xt_sqd_ij(SEXP x_dateSEXP, SEXP i_idxSEXP, SEXP j_idxSEXP, SEXP id_idxSEXP, SEXP id_nocSEXP, SEXP backfillSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::DoubleVector >::type x_date(x_dateSEXP );
        Rcpp::traits::input_parameter< const Rcpp::DoubleVector >::type i_idx(i_idxSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type j_idx(j_idxSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type id_idx(id_idxSEXP );
        Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type id_noc(id_nocSEXP );
        Rcpp::traits::input_parameter< const int >::type backfill(backfillSEXP );
        Rcpp::IntegerVector __result = stsm_xt_sqd_ij(x_date, i_idx, j_idx, id_idx, id_noc, backfill);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stsm_xt_mati_ij
int stsm_xt_mati_ij(const int x_date);
RcppExport SEXP sparsetsmat_stsm_xt_mati_ij(SEXP x_dateSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const int >::type x_date(x_dateSEXP );
        int __result = stsm_xt_mati_ij(x_date);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// stsm_xt_matd_ij
int stsm_xt_matd_ij(const double x_date);
RcppExport SEXP sparsetsmat_stsm_xt_matd_ij(SEXP x_dateSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const double >::type x_date(x_dateSEXP );
        int __result = stsm_xt_matd_ij(x_date);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
