# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wia <- function(i) {
    .Call('sparsetsmat_wia', PACKAGE = 'sparsetsmat', i)
}

stsm_xt_sqi_ij <- function(x_date, i_idx, j_idx, id_idx, id_noc, backfill) {
    .Call('sparsetsmat_stsm_xt_sqi_ij', PACKAGE = 'sparsetsmat', x_date, i_idx, j_idx, id_idx, id_noc, backfill)
}

stsm_xt_sqd_ij <- function(x_date, i_idx, j_idx, id_idx, id_noc, backfill) {
    .Call('sparsetsmat_stsm_xt_sqd_ij', PACKAGE = 'sparsetsmat', x_date, i_idx, j_idx, id_idx, id_noc, backfill)
}

stsm_xt_mati_ij <- function(x_date) {
    .Call('sparsetsmat_stsm_xt_mati_ij', PACKAGE = 'sparsetsmat', x_date)
}

stsm_xt_matd_ij <- function(x_date) {
    .Call('sparsetsmat_stsm_xt_matd_ij', PACKAGE = 'sparsetsmat', x_date)
}

