# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wia <- function(i) {
    .Call('sparsetsmat_wia', PACKAGE = 'sparsetsmat', i)
}

stsm_xt_sqi <- function(x_date, i_idx, j_idx, id_idx, id_noc, backfill) {
    .Call('sparsetsmat_stsm_xt_sqi', PACKAGE = 'sparsetsmat', x_date, i_idx, j_idx, id_idx, id_noc, backfill)
}

stsm_xt_sqd <- function(x_date, i_idx, j_idx, id_idx, id_noc, backfill) {
    .Call('sparsetsmat_stsm_xt_sqd', PACKAGE = 'sparsetsmat', x_date, i_idx, j_idx, id_idx, id_noc, backfill)
}

stsm_xt_mii <- function(i_idx, j_idx, x_date, id_idx, id_noc, backfill) {
    .Call('sparsetsmat_stsm_xt_mii', PACKAGE = 'sparsetsmat', i_idx, j_idx, x_date, id_idx, id_noc, backfill)
}

stsm_xt_mid <- function(i_idx, j_idx, x_date, id_idx, id_noc, backfill) {
    .Call('sparsetsmat_stsm_xt_mid', PACKAGE = 'sparsetsmat', i_idx, j_idx, x_date, id_idx, id_noc, backfill)
}

